Repository zowe/zowe-native-proto, pull requests merged in 2025-05, with the labels that each got.

#298 quick fix for undefined profile
  packages/cli/src/config/setup/Setup.handler.ts
Labels: size/S

#317 Fix/found private key cancel
  packages/sdk/src/AbstractConfigManager.ts
Labels: size/M

#305 introduce compress data set
  native/c/makefile
  native/c/test/main.c
  native/c/test/makefile
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zecb.h
  native/c/zmetal.h
  native/c/zowex.cpp
  native/c/zutm.c
  native/c/zwto.h
Labels: size/L

#306 Add test scripts for large file transfer
  examples/.gitignore
  examples/binary-ssh/package.json
  examples/binary-ssh/tests/base85-stream.ts
  examples/binary-ssh/tests/config.example.json
  examples/binary-ssh/tests/results.md
  examples/binary-ssh/tests/setup.sh
  examples/binary-ssh/tests/test-sftp.ts
  examples/binary-ssh/tests/test-ssh-b64.ts
  examples/binary-ssh/tests/test-ssh-b85.ts
  examples/binary-ssh/tests/test-ssh-raw.ts
  examples/binary-ssh/tests/test-znp.ts
  examples/binary-ssh/tests/test-zosmf.ts
  examples/binary-ssh/tests/testb64.go
  examples/binary-ssh/tests/testb85.go
  examples/binary-ssh/tests/testraw.go
  examples/binary-ssh/tests/utils.ts
  native/c/test/main.c
Labels: size/XL

#318 fix #188
  native/c/zattachx.h
  native/c/zcnm.c
  native/c/zdsm.c
  native/c/zjbm.c
  native/c/zutm.c
Labels: size/M

#328 Fix watch script exceeding max session limit
  scripts/watchNative.js
Labels: size/XS

#319 vsce: creating datasets with attributes
  native/golang/cmds/ds.go
  packages/cli/src/create/CreateDefaults.ts
  packages/cli/src/create/data-set/DataSet.definition.ts
  packages/cli/src/create/data-set/DataSet.handler.ts
  packages/vsce/src/api/SshMvsApi.ts
Labels: size/M

#311 Support streaming for read/write uss requests
  native/CHANGELOG.md
  native/c/extern/zb64.h
  native/c/zowex.cpp
  native/c/ztype.h
  native/c/zusf.cpp
  native/c/zusf.hpp
  native/c/zut.cpp
  native/c/zut.hpp
  native/golang/cmds/uss.go
  native/golang/tygo.yaml
  native/golang/types/common/common.go
  native/golang/types/uss/requests.go
  native/golang/types/uss/responses.go
  package-lock.json
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/doc/gen/cmds.ts
  packages/sdk/src/doc/gen/common.ts
  packages/sdk/src/doc/gen/ds.ts
  packages/sdk/src/doc/gen/jobs.ts
  packages/sdk/src/doc/gen/uss.ts
  packages/sdk/test/ZSshClient.test.ts
  packages/vsce/src/api/SshUssApi.ts
  scripts/updateLicenses.js
Labels: size/XXL

#307 create data sets with attributes
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zowex.cpp
  native/golang/cmds/ds.go
  native/golang/types/common/common.go
  native/golang/types/ds/requests.go
  packages/cli/src/create/CreateDefaults.ts
  packages/cli/src/create/data-set/DataSet.definition.ts
  packages/cli/src/create/data-set/DataSet.handler.ts
  packages/sdk/src/doc/gen/common.ts
  packages/sdk/src/doc/gen/ds.ts
  packages/vsce/src/api/SshMvsApi.ts
Labels: size/XL

#326 feat: Support streaming for read/write DS
  native/CHANGELOG.md
  native/c/extern/zb64.h
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zowex.cpp
  native/golang/cmds/ds.go
  native/golang/types/ds/requests.go
  packages/sdk/CHANGELOG.md
  packages/sdk/src/doc/gen/ds.ts
Labels: size/L

#327 feat: Support listing `recfm` for data sets, respect `recfm` for r/w ops
  native/CHANGELOG.md
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zdstype.h
  native/c/zowex.cpp
Labels: size/L

#333 Remove extraneous dependency on core SDK
  biome.json
  package-lock.json
  packages/cli/src/config/Config.definition.ts
  packages/cli/src/config/setup/Setup.handler.ts
  packages/cli/src/download/data-set/DataSet.handler.ts
  packages/cli/src/download/job-file/JobFile.handler.ts
  packages/cli/src/download/uss-file/UssFile.handler.ts
  packages/cli/src/server/uninstall/Uninstall.handler.ts
  packages/cli/src/submit/ds/Dataset.handler.ts
  packages/sdk/src/AbstractConfigManager.ts
  packages/vsce/src/SshClientCache.ts
Labels: size/S

#336 dev: Upload source files to z/OS much faster
  scripts/buildTools.ts
Labels: size/M
