Repository zowe/zowe-native-proto, pull requests merged in 2025-08, with the labels that each got.

#464 dev: optimize default make target
  README.md
  native/c/makefile
  package.json
  scripts/buildTools.ts
Labels: size/M, no-changelog

#421 feat(uss): Provide file tags and extra stats, add auto-detect encoding
  native/CHANGELOG.md
  native/c/test/ztest.hpp
  native/c/test/zusf.test.cpp
  native/c/zowex.cpp
  native/c/zusf.cpp
  native/c/zusf.hpp
  native/c/zut.cpp
  native/c/zut.hpp
  native/golang/cmds/uss.go
  native/golang/types/common/common.go
  native/golang/types/uss/requests.go
  packages/cli/CHANGELOG.md
  packages/cli/src/download/data-set/DataSet.definition.ts
  packages/cli/src/download/data-set/DataSet.handler.ts
  packages/cli/src/download/uss-file/UssFile.definition.ts
  packages/cli/src/download/uss-file/UssFile.handler.ts
  packages/cli/src/list/uss-files/UssFiles.definition.ts
  packages/cli/src/list/uss-files/UssFiles.handler.ts
  packages/cli/src/upload/file-to-uss/FileToUss.definition.ts
  packages/cli/src/upload/file-to-uss/FileToUss.handler.ts
  packages/cli/src/view/uss-file/UssFile.handler.ts
  packages/sdk/CHANGELOG.md
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/doc/gen/common.ts
  packages/sdk/src/doc/gen/uss.ts
  packages/sdk/src/doc/types.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/src/api/SshUssApi.ts
Labels: size/XXL

#467 fix(uss): Prioritize user-specified encoding over file tag when reading/writing USS files
  native/CHANGELOG.md
  native/c/zusf.cpp
  packages/cli/src/download/uss-file/UssFile.handler.ts
  packages/cli/src/upload/file-to-uss/FileToUss.handler.ts
  packages/cli/src/view/uss-file/UssFile.handler.ts
Labels: size/L

#358 Use streams for reading/writing data sets and USS files
  native/CHANGELOG.md
  native/c/zbase64.h
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zowex.cpp
  native/c/zusf.cpp
  native/c/zusf.hpp
  native/c/zut.cpp
  native/golang/cmds/ds.go
  native/golang/cmds/uss.go
  native/golang/types/ds/requests.go
  native/golang/types/ds/responses.go
  native/golang/types/uss/responses.go
  packages/cli/CHANGELOG.md
  packages/cli/src/download/data-set/DataSet.handler.ts
  packages/cli/src/download/job-file/JobFile.handler.ts
  packages/cli/src/download/uss-file/UssFile.handler.ts
  packages/cli/src/upload/file-to-data-set/FileToDataSet.definition.ts
  packages/cli/src/upload/file-to-data-set/FileToDataSet.handler.ts
  packages/cli/src/upload/file-to-uss/FileToUss.handler.ts
  packages/cli/src/view/uss-file/UssFile.handler.ts
  packages/sdk/CHANGELOG.md
  packages/sdk/src/CountingBase64Decode.ts
  packages/sdk/src/RpcNotificationManager.ts
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/doc/gen/cmds.ts
  packages/sdk/src/doc/gen/common.ts
  packages/sdk/src/doc/gen/ds.ts
  packages/sdk/src/doc/gen/jobs.ts
  packages/sdk/src/doc/gen/uss.ts
  packages/sdk/src/doc/types.ts
  packages/sdk/test/ZSshClient.test.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/src/api/SshMvsApi.ts
  packages/vsce/src/api/SshUssApi.ts
Labels: size/XXL

#474 fix: Refactor base64 encoding to handle leftover bytes correctly
  native/c/zbase64.h
  native/c/zds.cpp
  native/c/zusf.cpp
  package-lock.json
Labels: size/L

#471 Timeout Console Requests
  native/CHANGELOG.md
  native/asmmac/ZWEEPILG
  native/asmmac/ZWEPROLG
  native/c/examples/timer/testtime.c
  native/c/zcn.cpp
  native/c/zcnm.c
  native/c/zcnm31.c
  native/c/zcntype.h
  native/c/zecb.h
  native/c/zmetal.h
  native/c/zowex.cpp
  native/c/zutm.c
Labels: size/L

#476 fix(ci): Update version of native build in release workflow
  .github/workflows/release.yml
  .github/workflows/zos-build.yml
  scripts/buildTools.ts
Labels: size/M

#426 Feat/progress messages
  .github/workflows/zos-build.yml
  config.example.yaml
  native/c/makefile
  native/c/test/makefile
  native/c/zowex.cpp
  native/c/zshmem.cpp
  native/c/zshmem.hpp
  native/c/zusf.cpp
  native/golang/cmds/uss.go
  native/golang/main.go
  native/golang/types/uss/requests.go
  native/golang/utils/stdio.go
  native/golang/worker.go
  packages/cli/CHANGELOG.md
  packages/cli/src/download/uss-file/UssFile.handler.ts
  packages/cli/src/upload/file-to-uss/FileToUss.handler.ts
  packages/sdk/CHANGELOG.md
  packages/sdk/src/AbstractRpcClient.ts
  packages/sdk/src/ProgressTransform.ts
  packages/sdk/src/RpcNotificationManager.ts
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/doc/gen/uss.ts
  packages/sdk/src/doc/types.ts
  scripts/buildTools.ts
Labels: size/XL

#479 Fix Link Warning
  native/c/test/makefile
  native/c/zrecovery.h
Labels: size/XS

#477 Console Timeout Indicator
  native/CHANGELOG.md
  native/asmchdr/ihavra.s
  native/c/chdsect/ihavra.h
  native/c/examples/rcvy/testrcvy.c
  native/c/examples/timer/testtime.c
  native/c/zcnm.c
  native/c/zcntype.h
  native/c/zecb.h
  native/c/zowex.cpp
  native/c/zrecovery.h
Labels: size/L

#478 fix: Prevent unnecessary keyring prompts when using private key
  packages/sdk/CHANGELOG.md
  packages/sdk/src/AbstractConfigManager.ts
Labels: size/S

#495 refactor(lexer): support all characters as part of an identifier
  native/CHANGELOG.md
  native/c/lexer.hpp
Labels: size/XS

#501 Fix zowex --no-warn ends with rc != 0
  native/CHANGELOG.md
  native/c/zowex.cpp
  scripts/buildTools.ts
Labels: size/S

#509 fix: duplicate submit in submit-jcl handler
  native/CHANGELOG.md
  native/c/zowex.cpp
Labels: size/S

#514 Reduce worker count and restrict log file permissions
  .clang-format
  native/CHANGELOG.md
  native/c/zlogger.hpp
  native/c/zlogger_metal.c
  native/golang/utils/log.go
  packages/sdk/CHANGELOG.md
  packages/sdk/src/ZSshClient.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/package.json
  packages/vsce/src/SshClientCache.ts
Labels: size/M

#510 fix: Load dsorg from VTOC instead of calling fopen
  native/CHANGELOG.md
  native/c/zds.cpp
  native/c/zdsm.c
  native/c/zdsm.h
  native/c/zdstype.h
Labels: size/L

#518 Add `ZSHMEM_ENABLE` flag to remove zshmem dep for extenders
  native/c/makefile
  native/c/test/makefile
  native/c/zusf.cpp
Labels: size/M

#530 fix(ds/list): error when listing if OBTAIN fails
  native/CHANGELOG.md
  native/c/zds.cpp
Labels: size/XS
