Repository zowe/zowe-native-proto, pull requests merged in 2025-09, with the labels that each got.

#539 fix(vsce): Ensure that ISession is defined on node session
  packages/vsce/CHANGELOG.md
  packages/vsce/src/api/SshCommonApi.ts
Labels: size/XS

#534 Improve invalid private key UX; address rspack breakpoints issue
  package-lock.json
  packages/cli/CHANGELOG.md
  packages/cli/src/SshBaseHandler.ts
  packages/cli/src/config/setup/Setup.handler.ts
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/AbstractConfigManager.ts
  packages/sdk/src/ConfigFileUtils.ts
  packages/sdk/src/ZClientUtils.ts
  packages/sdk/src/ZSshUtils.ts
  packages/sdk/src/doc/gui.ts
  packages/sdk/src/index.ts
  packages/sdk/tests/AbstractConfigManager.test.ts
  packages/sdk/tests/ConfigFileUtils.test.ts
  packages/sdk/tests/ZSshClient.test.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/rspack.config.js
  packages/vsce/src/SshConfigUtils.ts
  packages/vsce/src/api/SshCommonApi.ts
Labels: size/XXL

#569 Reduce size of build-out folder generated for tests
  native/c/test/makefile
Labels: size/L

#571 fix: Retry button should invoke `installServer/uninstallServer` again
  packages/sdk/src/ZSshUtils.ts
Labels: size/XS, no-changelog

#580 Update `tar-fs` transitive dependency for audit
  package-lock.json
Labels: size/XS
