Repository zowe/zowe-native-proto, pull requests merged in 2025-06, with the labels that each got.

#339 Fix artifact download in release workflow
  .github/workflows/release.yml
  package.json
  scripts/moveArtifacts.js
Labels: size/S

#357 ci: Fix GH project status for pull requests
  .github/workflows/update-project.yml
Labels: size/XS

#352 Update release workflow to upload to JFrog
  .github/release.config.js
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/zos-build.yml
Labels: size/M

#341 feat: support listing permissions for USS files/folders, hide hidden files by default
  native/CHANGELOG.md
  native/c/zds.cpp
  native/c/zowex.cpp
  native/c/zusf.cpp
  native/c/zusf.hpp
  native/c/zut.cpp
  native/c/zut.hpp
  native/golang/cmds/uss.go
  native/golang/tygo.yaml
  native/golang/types/common/common.go
  packages/sdk/CHANGELOG.md
  packages/sdk/src/doc/gen/cmds.ts
  packages/sdk/src/doc/gen/common.ts
  packages/sdk/src/doc/gen/ds.ts
  packages/sdk/src/doc/gen/jobs.ts
  packages/sdk/src/doc/gen/uss.ts
  packages/sdk/src/doc/types.ts
  packages/vsce/src/SshClientCache.ts
  packages/vsce/src/SshConfigUtils.ts
  packages/vsce/src/Utilities.ts
  packages/vsce/src/api/SshUssApi.ts
Labels: size/L

#337 Refactor build tool and npm scripts
  .github/workflows/zos-build.yml
  .gitignore
  README.md
  config.default.jsonc
  config.example.yaml
  doc/troubleshooting.md
  package-lock.json
  package.json
  scripts/buildTools.ts
  scripts/watchNative.js
Labels: size/XXL

#351 refactor(zds): use VTOC to obtain recfm
  native/CHANGELOG.md
  native/c/zds.cpp
  native/c/zdsm.c
  native/c/zdsm.h
  native/c/zdstype.h
Labels: size/L

#361 feat: Add C++ lexer & CLI parser
  examples/native-cli/testcli.cpp
  native/CHANGELOG.md
  native/c/compat.hpp
  native/c/lexer.hpp
  native/c/makefile
  native/c/parser.hpp
  native/c/zcli.hpp
  native/c/zowex.cpp
  native/c/zstorage.h
  native/golang/cmds/ds.go
  native/golang/cmds/jobs.go
  native/golang/cmds/uss.go
  native/golang/utils/stdio.go
Labels: size/XXL

#388 refactor: remove --n alias for "negated flag" generation
  native/c/parser.hpp
  native/c/zowex.cpp
Labels: size/S

#393 S0c4 zcn put
  .clang-format
  .vscode/extensions.json
  .vscode/settings.json
  native/CHANGELOG.md
  native/c/examples/metal/demometal.c
  native/c/examples/metal/makefile
  native/c/examples/zcn/demozcn.cpp
  native/c/zcnm31.c
  native/c/zmetal.h
Labels: size/L

#396 Fix/parse cases
  native/c/lexer.hpp
  native/c/parser.hpp
  native/golang/cmds/ds.go
Labels: size/XXL
