Repository zowe/zowe-native-proto, pull requests merged in 2025-07, with the labels that each got.

#399 Support capturing lambdas in `ztest`, fix mode parsing for `zusf_chmod_uss_file_or_dir`
  native/CHANGELOG.md
  native/c/makefile
  native/c/test/makefile
  native/c/test/ztest.cpp
  native/c/test/ztest.hpp
  native/c/test/ztest_runner.cpp
  native/c/test/zusf.test.cpp
  native/c/test/zusf.test.hpp
  native/c/zowex.cpp
  native/c/zusf.cpp
  native/c/zusf.hpp
Labels: size/L

#404 fix: Bundle all dependencies in CLI tgz except cpu-features
  package-lock.json
  packages/cli/package.json
  scripts/bundleCliTgz.js
Labels: size/XS

#415 doc: Add architecture diagrams, example of adding new command
  doc/architecture-comparisons.md
  examples/add-new-command/native/c/zowex.cpp
  examples/add-new-command/native/golang/cmds/cmds.go
  examples/add-new-command/native/golang/cmds/definitions.go
  examples/add-new-command/native/golang/types/cmds/requests.go
  examples/add-new-command/native/golang/types/cmds/responses.go
  examples/add-new-command/packages/cli/src/issue/Issue.definition.ts
  examples/add-new-command/packages/cli/src/issue/ping/PingCommand.definition.ts
  examples/add-new-command/packages/cli/src/issue/ping/PingCommand.handler.ts
  examples/add-new-command/packages/sdk/src/AbstractRpcClient.ts
  examples/add-new-command/packages/sdk/src/doc/gen/cmds.ts
  examples/add-new-command/packages/vsce/src/api/SshCommandApi.ts
Labels: size/XXL, no-changelog

#407 refactor ztest to be header only and add xunit reporting
  examples/tests/.gitignore
  examples/tests/makefile
  examples/tests/more.cpp
  examples/tests/more.hpp
  examples/tests/runner.cpp
  native/c/test/makefile
  native/c/test/ztest.cpp
  native/c/test/ztest.hpp
Labels: size/XXL

#423 ci: Publish prerelease to Zowe Artifactory
  .github/workflows/release.yml
Labels: size/S, no-changelog

#447 feat: zowex --version, zowex version cmd
  native/CHANGELOG.md
  native/c/makefile
  native/c/zowex.cpp
  scripts/buildTools.ts
Labels: size/M

#450 feat: add full_status to rfc output of view status cmd
  native/CHANGELOG.md
  native/c/zjb.cpp
  native/c/zowex.cpp
Labels: size/XS
