Repository zowe/zowe-native-proto, pull requests merged in 2025-02, with the labels that each got.

#155 fix(zusf): avoid use of append in recursive logic
  native/c/zowex.cpp
  native/c/zusf.cpp
Labels: size/S

#160 Fix --encoding option for view commands
  native/c/zut.cpp
  native/golang/cmds/ds.go
  native/golang/cmds/jobs.go
  native/golang/cmds/uss.go
  native/golang/utils/bytes.go
  native/golang/utils/zos.go
  packages/vsce/src/api/SshMvsApi.ts
  packages/vsce/src/api/SshUssApi.ts
Labels: size/M

#159 lint: a few suggestions for resolving the lint issues
  package-lock.json
  packages/cli/src/issue/console/ConsoleCommand.definition.ts
  packages/cli/src/list/data-set-members/DataSetMembers.definition.ts
  packages/cli/src/list/data-set/DataSet.definition.ts
  packages/cli/src/list/jobs/Jobs.definition.ts
  packages/cli/src/list/uss-files/UssFiles.definition.ts
  packages/cli/src/server/install/Install.definition.ts
  packages/cli/src/server/uninstall/Uninstall.definition.ts
  packages/cli/src/upload/file-to-data-set/FileToDataSet.definition.ts
  packages/cli/src/upload/file-to-data-set/FileToDataSet.handler.ts
  packages/cli/src/upload/file-to-uss-file/FileToUssFile.definition.ts
  packages/cli/src/upload/file-to-uss-file/FileToUssFile.handler.ts
  packages/cli/src/view/data-set/DataSet.definition.ts
  packages/sdk/src/ZClientUtils.ts
  packages/sdk/src/ZSshUtils.ts
  packages/vsce/package.json
  packages/vsce/src/SshConfigUtils.ts
  packages/vsce/src/api/SshUssApi.ts
Labels: size/M

#162 chore: add missing changelog for changes in #143
  native/CHANGELOG.md
Labels: size/XS

#154 Pass zowex return codes through I/O server
  native/c/zcli.hpp
  native/c/zowex.cpp
  native/golang/cmds/cmds.go
  native/golang/cmds/dispatcher.go
  native/golang/cmds/ds.go
  native/golang/cmds/jobs.go
  native/golang/cmds/uss.go
  native/golang/main.go
  native/golang/types/common/common.go
  native/golang/utils/stdio.go
Labels: size/L

#164 fix: `watch:native` and `zowex job list`
  native/c/makefile
  scripts/buildTools.ts
  scripts/watchNative.js
Labels: size/M
