Repository zowe/zowe-native-proto, pull requests merged in 2025-04, with the labels that each got.

#266 Fix checksum generation in the build tool
  scripts/buildTools.ts
Labels: size/XS

#267 Add zoweax to server PAX release artifact
  .github/workflows/release.yml
  .github/workflows/zos-build.yml
  package.json
  scripts/buildTools.ts
Labels: size/S

#270 Open log file in read-only mode in VSCE
  packages/vsce/src/Utilities.ts
Labels: size/XS

#265 Introduce custom prolog / epilog to fix memory leak in recovery routines
  native/asmmac/ZWEEPILG
  native/asmmac/ZWEPROLG
  native/c/makefile
  native/c/test/makefile
  native/c/test/testrcvy.c
  native/c/zmetal.h
  native/c/zrecovery.h
Labels: size/L

#272 Add Parms to Run
  native/c/zadata.hpp
  native/c/zowex.cpp
Labels: size/L

#273 Add keep-alive messages to keep SSH connection active
  packages/sdk/CHANGELOG.md
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/ZSshUtils.ts
  packages/sdk/src/doc/client.ts
  packages/sdk/test/ZSshClient.test.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/package.json
  packages/vsce/src/SshClientCache.ts
Labels: size/M

#274 Return Job Correlator on Submit and List
  .vscode/settings.json
  native/c/zcli.hpp
  native/c/zjb.cpp
  native/c/zjb.hpp
  native/c/zjbm.c
  native/c/zjbtype.h
  native/c/zowex.cpp
Labels: size/L

#279 create loadlib wrapper
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zowex.cpp
Labels: size/M

#283 No wait option console
  native/c/zowex.cpp
Labels: size/S

#285 add --wait to zowex job submit
  native/c/zowex.cpp
Labels: size/M

#281 Fix checksums.asc not bundled in the vsce
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/zos-build.yml
Labels: size/S

#288 Add `--return-etag` flag so displaying etag is optional
  native/c/zadata.hpp
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zdstype.h
  native/c/zowex.cpp
  native/c/zusf.cpp
  native/c/zusf.hpp
  native/c/zusftype.h
  native/golang/cmds/ds.go
  native/golang/cmds/uss.go
Labels: size/M

#295 fix: don't fail the command if wait is not specified :yum:
  native/c/zowex.cpp
Labels: size/XS

#263 Cli config setup
  .vscode/launch.json
  package-lock.json
  package.json
  packages/cli/package.json
  packages/cli/src/config/Config.definition.ts
  packages/cli/src/config/setup/Setup.definition.ts
  packages/cli/src/config/setup/Setup.handler.ts
  packages/sdk/src/AbstractConfigManager.ts
  packages/sdk/src/ZClientUtils.ts
  packages/vsce/src/SshConfigUtils.ts
Labels: size/L

#268 Make sure we use the active subsystem instead of `JES2`
  .vscode/settings.json
  doc/todo.md
  native/c/zcli.hpp
  native/c/zds.cpp
  native/c/zjbm.c
  native/c/zjbtype.h
  native/c/zowex.cpp
  native/c/zut.cpp
  package-lock.json
Labels: size/L
