Repository zowe/zowe-native-proto, pull requests merged in 2025-03, with the labels that each got.

#149 Use JsonRPC in middleware and client
  README.md
  native/c/zcli.hpp
  native/c/zowex.cpp
  native/golang/cmds/cmds.go
  native/golang/cmds/dispatcher.go
  native/golang/cmds/ds.go
  native/golang/cmds/jobs.go
  native/golang/cmds/uss.go
  native/golang/main.go
  native/golang/tygo.yaml
  native/golang/types/common/common.go
  native/golang/utils/bytes.go
  native/golang/utils/cmd.go
  native/golang/utils/log.go
  native/golang/utils/stdio.go
  package-lock.json
  packages/cli/package.json
  packages/cli/src/SshBaseHandler.ts
  packages/cli/src/submit/Submit.definition.ts
  packages/cli/src/submit/job/SubmitJcl.definition.ts
  packages/cli/src/submit/stdin/Stdin.definition.ts
  packages/cli/src/submit/stdin/Stdin.handler.ts
  packages/sdk/src/AbstractRpcClient.ts
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/doc/common.ts
  packages/sdk/src/doc/index.ts
  packages/sdk/src/doc/rpc.ts
Labels: size/XXL

#166 Add workflow to update GitHub project
  .github/workflows/update-project.yml
Labels: size/M

#167 fix: CLI dangling pointers; read resource contents into vector
  native/CHANGELOG.md
  native/c/makefile
  native/c/zcli.cpp
  native/c/zcli.hpp
  native/c/zds.cpp
  native/c/zusf.cpp
Labels: size/M

#163 Smart ssh connection cleanup
  packages/vsce/src/SshConfigUtils.ts
Labels: size/L

#138 zowex: Add the ability to cancel jobs
  .vscode/settings.json
  doc/apis.md
  native/CHANGELOG.md
  native/c/zcli.hpp
  native/c/zjb.cpp
  native/c/zjb.hpp
  native/c/zjblkup.h
  native/c/zjbm.c
  native/c/zjbm.h
  native/c/zowex.cpp
  native/golang/cmds/cmds.go
  native/golang/cmds/definitions.go
  native/golang/types/cmds/requests.go
  packages/cli/CHANGELOG.md
  packages/cli/src/delete/Delete.definition.ts
  packages/sdk/CHANGELOG.md
  packages/sdk/src/doc/cmds.ts
  packages/sdk/src/doc/common.ts
  packages/sdk/src/doc/ds.ts
  packages/sdk/src/doc/jobs.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/src/api/SshCommandApi.ts
  packages/vsce/src/api/SshJesApi.ts
  packages/vsce/src/api/index.ts
  packages/vsce/src/extension.ts
Labels: size/L

#173 fix(ds): Use same read process as `zds_read_from_dd` in `zds_read_from_dsn`
  native/c/zds.cpp
Labels: size/S

#174 fix(ds): use fread to prevent newline in binary DS
  native/c/zds.cpp
Labels: size/M

#176 fix: Add port to SSH client ID in vsce
  packages/vsce/src/SshClientCache.ts
  packages/vsce/src/SshConfigUtils.ts
  packages/vsce/src/api/SshCommandApi.ts
  packages/vsce/src/extension.ts
Labels: size/M

#179 Fix lint errors to make Biome happy
  .github/workflows/lint.yml
  biome.json
  native/golang/cmds/ds.go
  native/golang/tygo.yaml
  native/golang/utils/bytes.go
  native/golang/utils/log.go
  native/golang/utils/stdio.go
  native/golang/worker.go
  package.json
  packages/cli/src/create/Create.definition.ts
  packages/cli/src/create/data-set-member/DataSetMember.handler.ts
  packages/cli/src/delete/Delete.definition.ts
  packages/cli/src/submit/stdin/Stdin.definition.ts
  packages/sdk/src/ZClientUtils.ts
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/ZSshUtils.ts
  packages/sdk/src/doc/common.ts
  packages/sdk/src/doc/ds.ts
  packages/sdk/src/doc/gen/cmds.ts
  packages/sdk/src/doc/gen/common.ts
  packages/sdk/src/doc/gen/ds.ts
  packages/sdk/src/doc/gen/jobs.ts
  packages/sdk/src/doc/gen/uss.ts
  packages/sdk/src/doc/index.ts
  packages/sdk/src/doc/jobs.ts
  packages/sdk/src/doc/uss.ts
  packages/vsce/src/SshConfigUtils.ts
Labels: size/XXL

#177 Fix ssh deploy command ending prematurely
  package-lock.json
  packages/sdk/package.json
  packages/sdk/src/ZSshUtils.ts
Labels: size/M

#181 Fail make build for compiler and linker warnings
  native/c/makefile
Labels: size/S

#180 Fix auto restore for migrated data sets
  native/c/makefile
  native/c/zcli.cpp
  native/c/zcli.hpp
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zdsm.c
  native/c/zdsm.h
  native/c/zdstype.h
  native/c/zowex.cpp
  native/golang/cmds/ds.go
  native/golang/types/common/common.go
  packages/sdk/src/doc/gen/common.ts
  packages/vsce/src/api/SshMvsApi.ts
Labels: size/L

#103 Add logging to client packages
  package-lock.json
  packages/sdk/src/AbstractRpcClient.ts
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/ZSshUtils.ts
  packages/vsce/.vscodeignore
  packages/vsce/log4jsconfig.json
  packages/vsce/package.json
  packages/vsce/src/SshConfigUtils.ts
  packages/vsce/src/Utilities.ts
  packages/vsce/src/extension.ts
Labels: size/L

#182 Add support for `hold` and `release` job operations
  doc/apis.md
  native/CHANGELOG.md
  native/c/zowex.cpp
  native/golang/cmds/definitions.go
  native/golang/cmds/jobs.go
  native/golang/types/jobs/requests.go
  native/golang/types/jobs/responses.go
  packages/cli/CHANGELOG.md
  packages/cli/src/hold/Hold.definition.ts
  packages/cli/src/hold/job/Job.definition.ts
  packages/cli/src/hold/job/Job.handler.ts
  packages/cli/src/release/Release.definition.ts
  packages/cli/src/release/job/Job.definition.ts
  packages/cli/src/release/job/Job.handler.ts
  packages/sdk/CHANGELOG.md
  packages/sdk/src/AbstractRpcClient.ts
  packages/sdk/src/doc/gen/jobs.ts
Labels: size/L

#190 fix(client): Fix issues with deploy command
  packages/sdk/src/ZSshUtils.ts
  packages/vsce/src/SshConfigUtils.ts
  packages/vsce/src/Utilities.ts
  scripts/buildTools.ts
  scripts/watchNative.js
Labels: size/M

#187 Complete Basic Recovery Routines
  .vscode/settings.json
  native/asmchdr/ihasaver.s
  native/asmchdr/ihasdwa.s
  native/c/chdsect/ihasaver.h
  native/c/chdsect/ihasdwa.h
  native/c/test/makefile
  native/c/test/testrcvy.c
  native/c/zmetal.h
  native/c/zrecovery.h
  native/c/zwto.h
Labels: size/XXL

#185 fix(ds/list): Address inconsistent results (compared to z/OSMF) for DS search patterns
  native/CHANGELOG.md
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zowex.cpp
  packages/cli/CHANGELOG.md
  packages/cli/src/list/data-set/DataSet.handler.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/src/api/SshMvsApi.ts
Labels: size/M

#193 fix #186
  native/c/zcnm.c
  native/c/zdsm.c
  native/c/zjbm.c
  native/c/zutm.c
Labels: size/S

#194 chore(native): Rename `ioserver` binary to `zowed`
  .gitignore
  README.md
  doc/apis.md
  doc/server/ioserver_architecture.md
  native/c/makefile
  native/c/test.sh
  native/c/zowex.cpp
  native/golang/cmds/cmds.go
  native/golang/cmds/dispatcher.go
  native/golang/cmds/ds.go
  native/golang/cmds/jobs.go
  native/golang/cmds/uss.go
  native/golang/go.mod
  native/golang/main.go
  native/golang/tygo.yaml
  native/golang/types/cmds/requests.go
  native/golang/types/cmds/responses.go
  native/golang/types/ds/requests.go
  native/golang/types/ds/responses.go
  native/golang/types/jobs/requests.go
  native/golang/types/jobs/responses.go
  native/golang/types/uss/requests.go
  native/golang/types/uss/responses.go
  native/golang/utils/cmd.go
  native/golang/utils/log.go
  native/golang/worker.go
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/ZSshUtils.ts
  scripts/buildTools.ts
Labels: size/L

#195 zssh: Clean up command names to align with CLI
  packages/cli/src/imperative.ts
  packages/cli/src/issue/console/ConsoleCommand.definition.ts
  packages/cli/src/list/data-set-members/DataSetMembers.definition.ts
  packages/cli/src/list/jobs/Jobs.definition.ts
  packages/cli/src/list/spool-files/SpoolFiles.definition.ts
  packages/cli/src/list/uss-files/UssFiles.definition.ts
  packages/cli/src/recall/Recall.definition.ts
  packages/cli/src/recall/data-set/DataSet.definition.ts
  packages/cli/src/recall/data-set/DataSet.handler.ts
  packages/cli/src/upload/Upload.definition.ts
  packages/cli/src/upload/file-to-uss/FileToUss.definition.ts
  packages/cli/src/upload/file-to-uss/FileToUss.handler.ts
  packages/cli/src/view/job-file/JobFile.definition.ts
  packages/cli/src/view/job-status/JobStatus.definition.ts
Labels: size/M

#199 Define B64String type for cleaner handling of byte arrays
  doc/client/architecture.md
  native/golang/tygo.yaml
  native/golang/types/ds/requests.go
  native/golang/types/ds/responses.go
  native/golang/types/jobs/requests.go
  native/golang/types/jobs/responses.go
  native/golang/types/uss/requests.go
  native/golang/types/uss/responses.go
  packages/cli/src/submit/stdin/Stdin.handler.ts
  packages/cli/src/upload/file-to-data-set/FileToDataSet.handler.ts
  packages/cli/src/upload/file-to-uss/FileToUss.handler.ts
  packages/cli/src/view/data-set/DataSet.handler.ts
  packages/cli/src/view/job-file/JobFile.handler.ts
  packages/cli/src/view/uss-file/UssFile.handler.ts
  packages/sdk/src/ZSshUtils.ts
  packages/sdk/src/doc/gen/cmds.ts
  packages/sdk/src/doc/gen/ds.ts
  packages/sdk/src/doc/gen/jobs.ts
  packages/sdk/src/doc/gen/uss.ts
  packages/sdk/src/doc/index.ts
  packages/sdk/src/doc/types.ts
  packages/vsce/src/api/SshJesApi.ts
  packages/vsce/src/api/SshMvsApi.ts
  packages/vsce/src/api/SshUssApi.ts
Labels: size/L

#184 feat: add submit uss across the board
  doc/apis.md
  native/CHANGELOG.md
  native/c/zowex.cpp
  native/golang/cmds/definitions.go
  native/golang/cmds/jobs.go
  native/golang/types/jobs/requests.go
  native/golang/types/jobs/responses.go
  packages/cli/CHANGELOG.md
  packages/cli/src/submit/Submit.definition.ts
  packages/cli/src/submit/ds/Dataset.definition.ts
  packages/cli/src/submit/ds/Dataset.handler.ts
  packages/cli/src/submit/local-file/LocalFile.definition.ts
  packages/cli/src/submit/local-file/LocalFile.handler.ts
  packages/cli/src/submit/uss/Uss.definition.ts
  packages/cli/src/submit/uss/Uss.handler.ts
  packages/sdk/CHANGELOG.md
  packages/sdk/src/AbstractRpcClient.ts
  packages/sdk/src/doc/gen/jobs.ts
Labels: size/L

#202 fix: use get_option_value for get_option sanity check
  examples/native-cli/testcli.cpp
  native/c/zcli.hpp
  native/c/zowex.cpp
Labels: size/M

#203 fix(sdk): Add error callback and request timeout to SSH client
  packages/cli/src/SshBaseHandler.ts
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/doc/client.ts
  packages/sdk/src/doc/index.ts
  packages/vsce/src/SshClientCache.ts
Labels: size/L

#205 fix: No response from `zowed` when listing data sets w/ non-existent pattern
  native/CHANGELOG.md
  native/golang/cmds/ds.go
Labels: size/S

#208 Fix dangling promise that made commands hang
  packages/sdk/src/ZSshClient.ts
Labels: size/M

#206 Add release workflow and run build workflows on push
  .github/release.config.js
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/zos-build.yml
  package.json
  packages/vsce/package.json
Labels: size/L

#211 fix: newline in job ID after submit, use 1 worker for CLI plug-in
  native/CHANGELOG.md
  native/golang/cmds/jobs.go
  native/golang/utils/cmd.go
  native/golang/utils/stdio.go
  packages/cli/src/SshBaseHandler.ts
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/doc/client.ts
Labels: size/M

#210 Fix issues in release workflow
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: size/S

#213 Add trace logging to debug ssh connection issues
  packages/sdk/src/ZSshUtils.ts
Labels: size/XS

#212 fix(vsce): pass prefix to request for list jobs
  packages/vsce/src/api/SshJesApi.ts
Labels: size/XS

#197 feat: Detect remote conflicts when uploading data sets or USS files
  native/CHANGELOG.md
  native/c/zds.cpp
  native/c/zds.hpp
  native/c/zowex.cpp
  native/c/zusf.cpp
  native/c/zusf.hpp
  native/c/zut.cpp
  native/c/zut.hpp
  native/golang/cmds/ds.go
  native/golang/cmds/uss.go
  native/golang/types/ds/requests.go
  native/golang/types/ds/responses.go
  native/golang/types/uss/requests.go
  native/golang/types/uss/responses.go
  native/golang/utils/conv.go
  packages/cli/CHANGELOG.md
  packages/sdk/src/doc/gen/ds.ts
  packages/sdk/src/doc/gen/uss.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/src/api/SshMvsApi.ts
  packages/vsce/src/api/SshUssApi.ts
Labels: size/L

#209 chore: readmes & CLI plugin first steps
  packages/cli/README.md
  packages/cli/src/imperative.ts
  packages/sdk/README.md
  packages/vsce/README.md
Labels: size/L

#215 fix(release): don't persist credentials at checkout
  .github/workflows/release.yml
Labels: size/XS

#216 fix: s0c4 if `--etag-only` not specified on writes
  native/CHANGELOG.md
  native/c/zds.cpp
  native/c/zowex.cpp
  native/c/zusf.cpp
Labels: size/M

#218 Update release config for Octorelease fixes
  .github/release.config.js
  .github/workflows/release.yml
Labels: size/XS

#219 fix(ds): E-tag mismatch when data set saved with encoding specified
  native/CHANGELOG.md
  native/c/zds.cpp
  packages/vsce/CHANGELOG.md
Labels: size/S

#224 add progress indicator to CLI and VSCE for deploying the server
  packages/cli/src/server/install/Install.handler.ts
  packages/sdk/src/ZSshUtils.ts
  packages/vsce/src/SshConfigUtils.ts
  packages/vsce/src/Utilities.ts
Labels: size/M

#237 async init for workers, remove WaitGroup
  native/CHANGELOG.md
  native/golang/main.go
  native/golang/types/common/options.go
  native/golang/utils/log.go
  native/golang/worker.go
  packages/sdk/src/doc/gen/common.ts
Labels: size/L

#230 validate ssh profiles when used on vsce
  packages/vsce/src/SshConfigUtils.ts
Labels: size/L

#242 Handle missing user in existing ssh profile
  packages/vsce/src/SshConfigUtils.ts
Labels: size/L

#236 Enhance logic to deploy server
  .github/workflows/build.yml
  .gitignore
  biome.json
  native/CHANGELOG.md
  native/golang/main.go
  native/golang/types/common/common.go
  native/golang/utils/bytes.go
  package-lock.json
  package.json
  packages/cli/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/ZSshClient.ts
  packages/sdk/src/ZSshUtils.ts
  packages/sdk/src/doc/gen/common.ts
  packages/sdk/test/ZSshClient.test.ts
  packages/sdk/test/mocks/ssh2.mock.ts
  packages/vsce/CHANGELOG.md
  packages/vsce/package.json
  packages/vsce/src/SshClientCache.ts
  packages/vsce/src/Utilities.ts
  packages/vsce/src/extension.ts
  scripts/buildTools.ts
Labels: size/XL

#244 vsce: Refactor `promptForProfile()`
  packages/vsce/src/SshConfigUtils.ts
Labels: size/L

#258 Add CI workflow for npm audit
  .github/workflows/audit.yml
Labels: size/S
